### ISSUE TITLE
Missing ArchiveIOException

### ISSUE THREAD

**Issue by brianium** [splitbrain/php-archive#1]
First off - awesome work! This functionality is a thing to come by for modern PHP.

While I was using this, I saw that the ArchiveIOException was not included - I was able to easily rectify the problem by adding it, but was unsure if there was a reason it was omitted, or if you had more specialized function in mind for that exception.

Also - any plans to tag a 1.0.0 release so its easier to include in other packages?

Again, awesome work!

**Comment by splitbrain** [comment]
ArchiveIOException is defined at the end of src/Archive.php, I just added some tests to make sure it works as expected. Did you have trouble with the Exceptions?

Re: versioning. This is my first own composer package ever. Is it enough to simply git tag it?

**Comment by brianium** [comment]
Due to the nature of the composer autoloader, classes are not included until asked for. I received the error "ArchiveIOException not found" when only using the `Zip` class - as it could not find the exception class because Archive.php is not included in the `Zip` file.

Putting the exception classes in their own files - named after the class - should fix the issue.

As for tagging 1.0.0 - yes: you can just add a git tag of "1.0.0" and then go to [packagist.org](https://packagist.org/) and update your package with a button. If you enable the composer hook for the package via packagist, it will update the available package every time you push a new tag.

Let me know if you have any more questions.

**Comment by brianium** [comment]
It looks like the intention was for `Zip` and `Tar` to extend `Archive`? Extending that class in `Zip` and `Tar` should fix the issue I'm having as well.

**Comment by splitbrain** [comment]
Ah, you're right. Tar was already extending it but I forgot it in Zip. Should be fixed now.
