### ISSUE TITLE
support zipping large files

### ISSUE THREAD

**Issue by jmcbee** [splitbrain/php-archive#11]
[Currenty Zip->addFile uses `file_get_contents`](https://github.com/splitbrain/php-archive/blob/a8881f4e072240f780a57d18c5a47690480d3f3c/src/Zip.php#L288) which limits you to the memory you have.
##

**Comment by Jackysi** [comment]
The zip is also limited to 4GB no matter the memory which is the max zip size. This could be avoided by somehow implementing zip64 but I have no idea how

**Comment by enricodias** [comment]
Regardless of the zip limit, 4GB of ram is a lot. The function addFile should add the file headers and the addData should have a loop to add a few MB on each iteration.

**Comment by splitbrain** [comment]
this has been fixed with #35
