### ISSUE TITLE
32bit PHP Problem

### ISSUE THREAD

**Issue by Jackysi** [splitbrain/php-archive#13]
I have this weird usage of this class to create backup on a data storage server, I know its strange but I have some special needs and I decided to go with PHP. Now the problem is when I attempt to store a 3GB file which doesn't work because I get "File size exceeded". Basically I know that PHP is limited to 2GB because of the integer limit. 

Is there any work around to tar such files?

P.S.: I'm not using in-memory files, rather the "directly on file system" method because I'm aware of the issues using memory for large data.
##

**Comment by splitbrain** [comment]
Sorry, I don't think there is an easy workaround without introducing all kinds of extra dependencies.

**Comment by Jackysi** [comment]
I see. Thanks for response anyway!
