### ISSUE TITLE
Encoding issue when extracting files with 'umlaut' 

### ISSUE THREAD

**Issue by lisps** [splitbrain/php-archive#14]
If you try to decompress an archive that contains files with umlauts (e.g: broschüre.pdf) the file will look something like brosch,,re.pdf after decompression. 

We expect the issue to be located around line ~491 in Zip.php 
The output of header['filename'] after the following line has already lost the umlaut. 

`$header['filename'] = fread($this->fh, $header['filename_len']);`

**Comment by splitbrain** [comment]
How was the Zip file created? On what kind of file system? What encoding is that file system using? Can you provide a test file?

My guess is that the zip file was created on a non-utf8 file system and thus the encoding of the file name is messed up.

**Comment by lisps** [comment]
I'm using Windows 7 on a NTFS filesystem So I suppose the encoding of the filenames would be UTF-16. 

I had two diffrent ways to create the test data which both ended up with the same result, but heres how I made them: 

1. I created an *.txt file in the explorer, right-clicked it, pressed "send to zip-archive". Which created a zip archive using the windows built-in zip programm. 
2. I again created a *.txt file in the explorer and then packed it into a zip using Winrar. 

Both files ended up losing the umlauts after decompression. I can provide the files if necessary.

**Comment by splitbrain** [comment]
Yeah, please attach the files here.

**Comment by lisps** [comment]
Here are the files... "testwinrar.zip" is the archive that I zipped using WinRar and the "test.zip" is the one I zipped using the windows 7 built in ziptool.

[testwinrar.zip](https://github.com/splitbrain/php-archive/files/714116/testwinrar.zip)
[test.zip](https://github.com/splitbrain/php-archive/files/714115/test.zip)

**Comment by splitbrain** [comment]
Interestingly both files seem to encode the umlaut differently:

```
$ zipinfo issue14-test.zip 
Archive:  issue14-test.zip
Zip file size: 114 bytes, number of entries: 1
-rw-a--     2.0 fat        0 b- stor 17-Jan-18 13:50 t�st.txt
1 file, 0 bytes uncompressed, 0 bytes compressed:  0.0%
```

```
$ zipinfo issue14-testwinrar.zip 
Archive:  issue14-testwinrar.zip
Zip file size: 186 bytes, number of entries: 1
-rw-a--     3.1 fat        0 bx stor 17-Jan-18 14:31 tüst.txt
1 file, 0 bytes uncompressed, 0 bytes compressed:  0.0%
```

**Comment by splitbrain** [comment]
Whoa, I just wasted so much time, because I assumed both zips pack the same file. But the file in the Windows one is actually having ``täst.txt`` instead of ``tüst.txt`` :angry:

**Comment by lisps** [comment]
Hey. I'm sorry if the two filenames where misleading. They were just meant to be some random umlaut containing names. I'm sorry that they where so similiar yet not the same and led to confusion. 
The problem appeared with both filenames for me anyways. So both didn't work, I just used two diffrent zip tools for them. 
As far as I got to know, the problem is, that filenames in Windows aren't encoded in UTF-8. The tool or library thats used to unzip the files doesn't know in which encoding the filenames are in and so they break because they're encoded in UTF-8 or some other encoding. Not the Windows filename encoding at least. (Filename Encoding != Encoding of its contents) Zip Tools that run under Windows do have access to that information, and therefore they use the correct encoding. But a OS-indepent solution wouldn't know on which OS the files were zipped on... So its more general problem than a problem with the zip archive library I guess?

**Comment by splitbrain** [comment]
yeah, zip files expect CP437 filenames. If you have something not fitting into that you have to jump through additional hoops. I'm able to extract your files by now. currently working on making the compression work as well. I can decompress my own files, but unzip and 7zip can't. So I must doing something wrong but I'm not sure what.

**Comment by splitbrain** [comment]
Okay it should work now. Could you give a try before I tag a new release?
