### ISSUE TITLE
Use yield in contents() for lower memory usage

### ISSUE THREAD

**Issue by jgmdev** [splitbrain/php-archive#25]
First thanks for the work on such a nice library! Now to the issue:

The **contents()** function generates a whole array of FileInfo objects which can use a lot of ram if the file been read contains lots of entries. It seems that the **yield** keyword was introduced since PHP 5.5 ([generators](http://php.net/manual/en/language.generators.overview.php) - if that matters) and it is a great way of iterating over a list of data without having to store it inside an array first. Basically the yield keywords does all the magic as shown below:

```php
public function contents()
{
    if ($this->closed || !$this->file) {
        throw new ArchiveIOException('Can not read from a closed archive');
    }
    $result = array();
    while ($read = $this->readbytes(512)) {
        $header = $this->parseHeader($read);
        if (!is_array($header)) {
            continue;
        }
        $this->skipbytes(ceil($header['size'] / 512) * 512);
        yield $this->header2fileinfo($header);
    }
    $this->close();
}

// Can be iterated normally but each element is generated one at a time
foreach($archive->contents() as $object)
{
    //...
}
```
If returning an array is the intended behavior or to not break backward compatibility one can also introduce a new contents function with a suffix like contentsGenerator() or contentsYield(), not sure what whould be the best naming option here :)

**Comment by splitbrain** [comment]
excellent idea. I haven't worked with generators much but this seems a good application. can you send a pull request?

**Comment by jgmdev** [comment]
How would you like the pull request? use the contents() function or write another function that does the same using yield, and if the latter what function name to use?

**Comment by splitbrain** [comment]
I think adjusting the `contents()` method should be fine.

**Comment by jgmdev** [comment]
Just writing to reference pull #26 here.
