### ISSUE TITLE
Query: Are the .tars generated here free of the ustar size limitations?

### ISSUE THREAD

**Issue by AllAstronauts** [splitbrain/php-archive#27]
I took a cursory look at the source and see references to ustar and posix, but no clear statement/s regarding if these tars are coded to the more recent, and unlimited in size, tar file standards.

Phar is for all intents and purposes abandoned and stuck on ustar 8GB limits so if this does allow larger file sizes that would be not only great but should get more promotion all around.

**Comment by splitbrain** [comment]
I wouldn't recommend using this library for files that large. It's simply not meant and tested for that and you will probably run into memory and time limit problems way before coming close to 8GB.

Pull Requests to improve that are welcome of course.
