### ISSUE TITLE
Cannot open zip archive in both Linux and MS Windows

### ISSUE THREAD

**Issue by fedek6** [splitbrain/php-archive#5]
Hi,
There is information about invalid archive when I try to open it in Windows explorer (works in 7-zip) and Linux Kde Ark Version 2.19. Is there any fix for this problem?

**Comment by splitbrain** [comment]
This might be related to #3 for which I just pushed a fix. I'll see if I can check on a Windows system.

**Comment by splitbrain** [comment]
Looks like #3 did not fix it. So it might be related to #7 - don't know what's wrong, yet

**Comment by splitbrain** [comment]
fixed by #7
