### ISSUE TITLE
Tar creates archive corrupted?

### ISSUE THREAD

**Issue by jmcbee** [splitbrain/php-archive#9]
This is the code that I have used:

``` php
<?php
require 'vendor/autoload.php';
$callback = function( $file ) {
    return true;
};
$dir = new RecursiveIteratorIterator( new RecursiveDirectoryIterator( __DIR__ . DIRECTORY_SEPARATOR . 'src', FilesystemIterator::SKIP_DOTS ) );

$archive = new \splitbrain\PHPArchive\Tar();
$archive->setCompression( 9, \splitbrain\PHPArchive\Archive::COMPRESS_NONE );
$archive->create( 'foo.tar' );

/**
 * @var string $filename
 * @var SplFileInfo $file
 */
foreach ( $dir as $filename => $file ) {
    $relative = str_replace( __DIR__ . DIRECTORY_SEPARATOR . 'src' . DIRECTORY_SEPARATOR, '', $filename );
    $relative = str_replace( '\\', '/', $relative );
    echo 'Adding ' . $relative . "...\n";
    $archive->addFile( $filename, $relative );
}
$archive->close();
```

It only adds the first file and the rest just silently fails although there are no errors appearing. The first file doesn't have contents in the archive (`Test/Test.php`).

**Comment by jmcbee** [comment]
Hi @splitbrain,

Thank you so much for responding. That does indeed solve this error. Now another one pops up, this time when extracting. I added the following code to above

``` php
$archive->open( 'foo.tar' );
$archive->extract( sys_get_temp_dir() . '/foo' );
```

Which throws `Uncaught exception 'splitbrain\PHPArchive\ArchiveCorruptedException' with message 'Header does not match it's checksum' in vendor\splitbrain\php-archive\src\Tar.php:546`

**Comment by splitbrain** [comment]
Yeah, I made a mistake. Make sure you have the newest release (1.0.6). Report back if that still doesn't work.

**Comment by jmcbee** [comment]
Hello @splitbrain,
It succeeds to extract for tar, tar.gz but not tar.bz2. The exception thrown is `Header does not match it's checksum`.

**Comment by jmcbee** [comment]
@splitbrain  This is for when I have a filter on the `include` parameter only.

``` php
$archive->open( 'foo.tar.bz2' );
$archive->extract( sys_get_temp_dir() . '/foo', '', '', '/util\.php/' );
```

**Comment by jmcbee** [comment]
Sorry, I meant the `include` parameter. Edited previous comment.

**Comment by splitbrain** [comment]
Can you provide a test file?

**Comment by jmcbee** [comment]
https://gist.github.com/anonymous/ea526cbb8f4e1a5a0e37

**Comment by splitbrain** [comment]
pushed 1.0.7

**Comment by jmcbee** [comment]
Thanks! I'm glad I was able to help.
